### ISSUE TITLE
Won't stay connected to phone

### ISSUE THREAD

**Issue by wolfembers** [Android-Messages-For-Desktop/android-messages-for-desktop#22]
Hello, I have recently noticed that my phone will not stay connected (even with the toggle to stay connected switched on) for more than ~8 hours. This started occurring when Google removed the old `messages.android.com` website and replaced it with the new `messages.google.com`

**Comment by antoineguilbert** [comment]
Fixed with the last update https://github.com/Android-Messages-For-Desktop/android-messages-for-desktop/releases
