### ISSUE TITLE
Intego Virus Barrier reports dmg 1.1.3 is infected with OSX/Miner

### ISSUE THREAD

**Issue by echarlus** [Android-Messages-For-Desktop/android-messages-for-desktop#27]
After virus definition update today, Virus Barrier notified me that Android Message installed on my mac is infected by OSX/Miner malware.
I've re-downloaded and scanned the 1.1.3 dmg from github and the file is reported as infected...
<img width="601" alt="Capture d’écran 2020-10-23 à 10 57 34" src="https://user-images.githubusercontent.com/7509875/96978486-b3856c80-151e-11eb-99de-d7acc42d6882.png">

**Comment by antoineguilbert** [comment]
Fixed with the last update (normaly) https://github.com/Android-Messages-For-Desktop/android-messages-for-desktop/releases

**Comment by echarlus** [comment]
confirmed, warning is gone ! 
Thanks
