### ISSUE TITLE
[BUG] Android Messages won't work anymore, requiring an update to Chrome

### ISSUE THREAD

**Issue by foux** [Android-Messages-For-Desktop/android-messages-for-desktop#29]
Since today, the app won't work anymore, requiring an updated version of Chrome. Here is a screenshot of the issue (in french) : 
![image](https://user-images.githubusercontent.com/246550/104027115-3be2e780-51c7-11eb-93b6-8b8c0d28b2f6.png)

**Comment by foux** [comment]
This project seems dead for a couple of years now. For anyone looking for an alternative, I can recommand [Flotato](https://www.flotato.com/) which does the same thing for Android Message, and many more (basically any website you want)

**Comment by antoineguilbert** [comment]
Hello ! I've seen the bug this morning too. I'll try do release an update this week-end :)

**Comment by antoineguilbert** [comment]
Fix in the last release ! https://github.com/Android-Messages-For-Desktop/android-messages-for-desktop/releases 👍
